[package]
name = "tflite"
version = "0.7.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]
description = "Rust bindings for TensorFlow Lite"
keywords = ["tensorflow", "tflite", "bindings"]
license = "MIT/Apache-2.0"
repository = "https://github.com/boncheolgu/tflite-rs"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/crate/tflite"

exclude = [
  "submodules/tensorflow/tensorflow/*.bzl",
  "submodules/tensorflow/tensorflow/*.lds",
  "submodules/tensorflow/tensorflow/*.py",
  "submodules/tensorflow/tensorflow/c",
  "submodules/tensorflow/tensorflow/cc",
  "submodules/tensorflow/tensorflow/compiler",
  "submodules/tensorflow/tensorflow/contrib",
  "submodules/tensorflow/tensorflow/core",
  "submodules/tensorflow/tensorflow/docs_src",
  "submodules/tensorflow/tensorflow/examples",
  "submodules/tensorflow/tensorflow/g3doc",
  "submodules/tensorflow/tensorflow/go",
  "submodules/tensorflow/tensorflow/java",
  "submodules/tensorflow/tensorflow/js",
  "submodules/tensorflow/tensorflow/lite/g3doc",
  "submodules/tensorflow/tensorflow/lite/java",
  "submodules/tensorflow/tensorflow/lite/python",
  "submodules/tensorflow/tensorflow/lite/testing",
  "submodules/tensorflow/tensorflow/lite/toco",
  "submodules/tensorflow/tensorflow/python",
  "submodules/tensorflow/tensorflow/stream_executor",
  "submodules/tensorflow/tensorflow/tools",
  "submodules/tensorflow/third_party/icu",
  "submodules/tensorflow/third_party/toolchains",
]

[dependencies]
cpp = "0.5"
failure = "0.1"
libc = "0.2"
maybe-owned = "0.3"

[build-dependencies]
bart = { version = "0.1", optional = true }
bart_derive = { version = "0.1", optional = true }
bindgen = "0.52"
cpp_build = "0.5"
fs_extra = { version = "1.1", optional = true }

[features]
build = ["fs_extra"]
default = ["build"]
debug_tflite = ["build"] # use "libtensorflow-lite.a" built in debug mode
generate_model_apis = ["bart", "bart_derive"]

[package.metadata.docs.rs]
all-features = false
no-default-features = true
default-target = "x86_64-unknown-linux-gnu"
